# Generated by Django 3.1.2 on 2024-10-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appcalculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
            ],
            options={
                'db_table': 'appcalculator',
            },
        ),
    ]
